/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rwash.views;
import javax.swing.JFrame;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JFrame;
/**
 *
 * @author aluno
 */
public class DashBoardCliente extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardCliente
     * @param idClienteLogado
     */
    public DashBoardCliente(int idClienteLogado) {
        initComponents();
        
         setTitle("Dashboard - Reuso de Água da Lavadora");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new java.awt.GridLayout(2, 2));

        // Leitura dos dados do CSV
        ArrayList<String> datas = new ArrayList<>();
        ArrayList<Double> turbidez = new ArrayList<>();
        ArrayList<Double> temperatura = new ArrayList<>();
        ArrayList<Double> consumoAgua = new ArrayList<>();
        ArrayList<Double> consumoEnergia = new ArrayList<>();

        try (BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\aluno\\Downloads\\R-Wash\\R-wash\\Rwash\\src\\main\\java\\com\\mycompany\\rwash\\views\\dados.csv"))) {
            String linha = br.readLine(); 
            while ((linha = br.readLine()) != null) {
                String[] partes = linha.split(",");
                datas.add(partes[0]);
                turbidez.add(Double.parseDouble(partes[1]));
                temperatura.add(Double.parseDouble(partes[2]));
                consumoAgua.add(Double.parseDouble(partes[3]));
                consumoEnergia.add(Double.parseDouble(partes[4]));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        String[] categorias = datas.toArray(new String[0]);
        double[] vTurbidez = turbidez.stream().mapToDouble(Double::doubleValue).toArray();
        double[] vTemp = temperatura.stream().mapToDouble(Double::doubleValue).toArray();
        double[] vAgua = consumoAgua.stream().mapToDouble(Double::doubleValue).toArray();
        double[] vEnergia = consumoEnergia.stream().mapToDouble(Double::doubleValue).toArray();

        // Adiciona gráficos ao dashboard
        add(new PainelGrafico("Turbidez", "Data", "NTU", categorias, vTurbidez));
        add(new PainelGrafico("Temperatura", "Data", "°C", categorias, vTemp));
        add(new PainelGrafico("Consumo de Água", "Data", "Litros", categorias, vAgua));
        add(new PainelGrafico("Consumo de Energia", "Data", "kWh", categorias, vEnergia));

        pack();
        setSize(900, 700);
        setLocationRelativeTo(null);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        ex.printStackTrace();
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            int idClienteTeste = 1; // valor fixo para teste sem login
            new DashBoardCliente(idClienteTeste).setVisible(true);
        }
    });
    }
         
      
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
